# Introduction to Python 

In [1]:
print("Hello, World")
print('Hello, World',"Diksha")

Hello, World
Hello, World Diksha


In [2]:
# print "fg" # Missing parentheses

In [3]:
pval=0.08
if pval<=0.05:
    print("Reject Ho with p-value as", pval)
    print("Hello")
else:
    print("Fail to reject Ho with p-value as", pval)
    print("End")
print("End Outside")

Fail to reject Ho with p-value as 0.08
End
End Outside


# Reserved Keywords

and, if, else, def, break, not, continue, for, goto, import, while, elif, return, print, from, class, with etc
Comment


Comment

In [4]:
# First Comment
x=2   # sample
x
# Multiple line comment """not working""" 

2

In [5]:
# Nonopndvanspo
# dnvsd

# Assigning values to Variables

In [6]:
a=2
b=3
print(a,b)

2 3


In [7]:
x,y=3,4
print(x,y)

3 4


In [8]:
x=y=1
print(x)
print(y)
y=2
print(y)
print(x+y)

1
1
2
3


In [9]:
x='Some String'
x

'Some String'

In [10]:
y="Another String"
x+y

'Some StringAnother String'

In [11]:
x,y,z="Diksha", 3, 5.4
z,y,x

(5.4, 3, 'Diksha')

# Standard Datatypes

   1. Number
   2. String
   3. List
   4. Tuples
   5. Dictionary

In [12]:
int_1,int_2,int_3=1, -2, 0
int_1,int_2,int_3

(1, -2, 0)

In [ ]:
float_1=3.1454373367
float_1

In [14]:
round(float_1,5)

3.14544

In [15]:
Long_1=124325849879460000005165156616543   # Long Number ????
Long_1

124325849879460000005165156616543

In [16]:
complex_1,complex_2=3.14j, 2+1.2j
complex_2+complex_1

(2+4.34j)

# String

In [17]:
str="abcdefghij"
str

'abcdefghij'

In [18]:
### indexing and Slicing
print(str)       # 0123456789
print(str[0])    # 0
print(str[0:3])  # 012
print(str[1:4])  # 123
print(str[-3])   # 7

abcdefghij
a
abc
bcd
h


In [19]:
str="Hello "
str+str+str

'Hello Hello Hello '

In [20]:
tstat=0.456005498
pval=0.002
print("The t-statistics value is %.5f, so the pvalue is %.3f"%(tstat,pval))

The t-statistics value is 0.45601, so the pvalue is 0.002


# Lists

In [21]:
list=["Manoj",816,2009,"Asst Prof",[2,3,4]]
list

['Manoj', 816, 2009, 'Asst Prof', [2, 3, 4]]

In [22]:
list2=[list, 23.6]
len(list2)

2

In [23]:
list[-2]

'Asst Prof'

In [24]:
list+list
len(list*3)

15

# Oprations on List

In [25]:
List1=[2,4,5,6,2,3]
print(max(List1))
print(min(List1))
List1.append(5)
print(List1)
List1.extend([5,8,9,0])
print(len(List1))
List1=List1.sort()
print(List1)

6
2
[2, 4, 5, 6, 2, 3, 5]
11
None


In [26]:
list
list[0]="Rajaa"
list

['Rajaa', 816, 2009, 'Asst Prof', [2, 3, 4]]

# Tuples

In [27]:
tuple1=('Manoj',23,1.2)
tuple1

('Manoj', 23, 1.2)

In [28]:
#tuple1[1]=32

In [29]:
tuple1*2

('Manoj', 23, 1.2, 'Manoj', 23, 1.2)

# Dictionary

In [30]:
dict1={'name':"Manoj",'Age':35,"Edu":"Stats"}
dict1

{'name': 'Manoj', 'Age': 35, 'Edu': 'Stats'}

In [31]:
dict1['name']

'Manoj'

In [33]:
# dict1[1]

In [32]:
dict1['Edu']

'Stats'

In [34]:
list1=["Manoj",35,'stat']
list1

['Manoj', 35, 'stat']

In [35]:
list2=[3,1,2]
list2+=[2,4,2,3]
list2

[3, 1, 2, 2, 4, 2, 3]

In [36]:
set1=set(list2)

In [37]:
set1

{1, 2, 3, 4}

In [38]:
#set1[1]

# Operators

    Arithmatic +, - , *, /, %, //, **

    Comparison < > == !=, <=, >=

    Assignment =, -=, +=, *=, /=, //=, %=, **=

    Logical and &&, or |, not !

    Boolean &, |, ^, ~

In [39]:
x,y=2,3

In [40]:
x**y

8

In [41]:
x==y

False

In [42]:
x!=y

True

In [43]:
#x<>y

# Some Functions

In [44]:
x=-34.563529645
abs(x)

34.563529645

In [45]:
import numpy 
y=5.6
numpy.ceil(y)

6.0

In [46]:
import numpy as np
x=48.6
np.ceil(x)

49.0

In [47]:
np.exp(3)

20.085536923187668

#                      Numpy Tutorial

Import Numpy

In [48]:
#!pip install numpy
import numpy as np

# Check Python and Numpy Version

In [49]:
import platform
print('Python version: ' + platform.python_version())
print('Numpy version: ' + np.__version__)

Python version: 3.9.7
Numpy version: 1.20.3


Numpy Data Types

A list of Numpy Data Types

In [50]:
import pandas as pd
dtypes = pd.DataFrame({'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']})
dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

# Create an array with a specified data type

In [51]:
arr = np.array([1,2,3.2],dtype='f2')
print("The datatype of ",arr," is ",arr.dtype)

The datatype of  [1.  2.  3.2]  is  float16


In [52]:
arr = np.array([1+2j, 3-4j], dtype=np.complex64)
print("The datatype of ",arr," is ",arr.dtype)

The datatype of  [1.+2.j 3.-4.j]  is  complex64


In [53]:
arr = np.array([0, 1, 1], dtype=bool)
print("The datatype of ",arr," is ",arr.dtype)

The datatype of  [False  True  True]  is  bool


# String data type

Set the max length of the string using S + some number, such as 'S3' any string longer than the max length will be truncated


In [54]:
s = np.array(['abc', 'defg'], dtype='S4')
print("The datatype of ",s," is ",s.dtype)

The datatype of  [b'abc' b'defg']  is  |S4


# Create Arrays

Create an Array From A Python Array

In [55]:
arr = np.array(range(1,10,2))
print(arr)

[1 3 5 7 9]


In [56]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


# Create an Array in a Specified Data Type

In [57]:
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


# Create An Array Of Evenly Spaced Values Within A Specified Interval

In [58]:
arr = np.arange(0, 20, 2)  # np.arange(start, stop, step)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


# Create An Array Of Evenly Spaced Numbers In A Specified Interval

In [59]:
# np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False) 
arr = np.linspace(0, 10, 3)
print(arr)

[ 0.  5. 10.]


In [60]:
# exclude endpoint and return step size
arr, step = np.linspace(0, 10, 5, endpoint=False, retstep=True)
print("array: ",arr)
print("step :",step)

array:  [0. 2. 4. 6. 8.]
step : 2.0


# Create An Array Of Random Values In A Given Shape

In [61]:
arr = np.random.rand(2, 3)
print(arr)

[[0.98710165 0.31965317 0.36703614]
 [0.12110528 0.89896295 0.14149117]]


# Create an Array of Zeros in a Given Shape

In [63]:
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


# Create An Array Of Zeros With The Same Shape And Data Type As A Given Array

In [64]:
zeros = np.zeros_like(np.array([[1,2,3,4],[3,4,5,6]]))
print(zeros)

[[0 0 0 0]
 [0 0 0 0]]


# Create An Array Of Ones In A Given Shape

In [65]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


# Create an array of ones with the same shape and data type as a given array

In [66]:
ones = np.ones_like(arr)
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


# Create an array of arbitrary values in a given shape

In [67]:
empty1 = np.empty((2,3))
print(empty1)

[[1. 1. 1.]
 [1. 1. 1.]]


# Create an array of arbitrary values with the same shape and data type as a given array

In [68]:
empty = np.empty_like(arr)
print(empty)

[[1. 1. 1.]
 [1. 1. 1.]]


# Create an array of constant values in a given shape

In [69]:
p = np.full((2,3), 5)
print(p)

[[5 5 5]
 [5 5 5]]


# Create an array of constant values with the same shape and data type as a given array

In [70]:
p = np.full_like(arr, 5)
print(p)

[[5. 5. 5.]
 [5. 5. 5.]]


# Create an array by repetition

Repeat each element of an array by a specified number of times


In [71]:
# np.repeat(iterable, reps, axis=None)
arr = np.array([[0, 1, 2],[3,4,5]])
print(arr)
print(np.repeat(arr, [1,2],axis=0))    # or np.repeat(range(3), 3)
type(arr)

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [3 4 5]]


numpy.ndarray

# Repeat along a specified axis with specified number of repetitions.

In [73]:
arr = [[1,2], [3,4]]
print(np.repeat(arr, [1,2], axis=1))

[[1 2 2]
 [3 4 4]]


# Repeat an array by a specified number of times

In [74]:
arr = [0, 1, 2]
print(np.tile(arr,(2,3)))

[[0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]]


In [75]:
# repeat along specified axes
print(np.tile(arr, (2,2)))

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


# create an identity matrix with a given diagonal size

In [76]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [77]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Create an identity matrix with a diagonal offset

In [260]:
identity_matrix = np.eye(5, k=1)    # positive number shifts the diagonal upward
print(identity_matrix)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [79]:
identity_matrix = np.eye(5, k=-2)   # negative number shifts the diagonal downward
print(identity_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Extract the diagonal array / create a diagonal array

In [80]:
arr = np.random.rand(4,4)
print(arr)

[[0.17845628 0.04522858 0.1731363  0.71552073]
 [0.74728047 0.83354046 0.40640678 0.54448897]
 [0.2279927  0.18544943 0.09331295 0.28249351]
 [0.04138785 0.45954829 0.38032347 0.47118742]]


In [81]:
print(np.diag(arr)) # extract the diagonal

[0.17845628 0.83354046 0.09331295 0.47118742]


In [82]:
arr = np.diag([1,2,3])    # create a matrix with a specified diagonal array
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


# Inspect Arrays

In [83]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

# Inspect general information of an array

In [84]:
print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x225db00c7c0
byteorder:  little
byteswap:  False
type: int64
None


# Inspect the data type of an array

In [85]:
print(arr.dtype)

int64


# inspect the dimension of an array

In [86]:
nrow, ncol =arr.shape
print(nrow, ncol)

2 3


# Inspect length of an array

In [87]:
print(len(arr))

2


# Inspect the number of dimensions of an array

In [88]:
print(arr.ndim)

2


# Inspect the number of elements in an array

In [89]:
print(arr.size)

6


# Inspect the number of bytes of each element in an array

In [90]:
print(arr.itemsize)

8


# Inspect the memory size of an array (in byte)

In [91]:
# arr.nbytes = arr.size * arr.itemsize
print(arr.nbytes)

48


# Sampling Methods

Set seed

In [93]:
np.random.seed(123)

# Generate a random sample from interval [0, 1) in a given shape

In [94]:
print(np.random.rand())   # generate a random scalar  

0.6964691855978616


In [95]:
print(np.random.rand(1,3))        # generate a 1-D array

[[0.28613933 0.22685145 0.55131477]]


In [96]:
print(np.random.rand(3,3))          # generate a 2-D array

[[0.71946897 0.42310646 0.9807642 ]
 [0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224]]


# Generate a sample from the standard normal distribution (mean = 0, var = 1)

In [97]:
print(np.random.randn(3,3))

[[-0.14337247 -0.6191909  -0.76943347]
 [ 0.57674602  0.12652592 -1.30148897]
 [ 2.20742744  0.52274247  0.46564476]]


# Generate an array of random integers in a given interval [low, high)

In [98]:
# np.ranodm.randint(low, high, size, dtype)
print(np.random.randint(1, 10, 30, 'i8'))

[5 7 2 6 7 3 2 9 4 6 1 3 7 3 5 5 7 4 1 7 5 8 7 8 2 6 8 3 5 9]


# Generate an array of random floating-point numbers in the interval [0.0, 1.0)

In [99]:
# the following methods are the same as np.random.rand()
print(np.random.random_sample(5))
print(np.random.random(5))
print(np.random.ranf(5))
print(np.random.sample(5))

[0.12062867 0.8263408  0.60306013 0.54506801 0.34276383]
[0.30412079 0.41702221 0.68130077 0.87545684 0.51042234]
[0.66931378 0.58593655 0.6249035  0.67468905 0.84234244]
[0.08319499 0.76368284 0.24366637 0.19422296 0.57245696]


# Sampling Discrete Distribution

Generate a random sample from a given Discrete Distribution


In [100]:
# np.random.choice(iterable_or_int, size, replace=True, p=weights)
print(np.random.choice(range(4), 10, replace=True, p=[0.1, 0.4, 0.4,0.1]))

[0 2 2 2 0 2 2 1 1 2]


In [113]:
print(np.random.choice(['a','b','c'], 10))

['a' 'a' 'a' 'a' 'b' 'c' 'c' 'c' 'a' 'b']


In [114]:
print(np.random.choice([1,2,3], 10))

[3 1 1 1 3 2 3 3 3 1]


# Sampling from Various Distributions

In [115]:
x=np.random.normal(loc=100,scale=10,size=10)
np.std(x)

8.755284423570027

In [116]:
np.random.binomial(n=10,p=0.3,size=10)

array([2, 2, 4, 3, 2, 3, 4, 5, 3, 2])

In [117]:
np.random.poisson(lam=3,size=5)
np.random.poisson(3,5)

array([3, 2, 4, 1, 3])

In [118]:
np.random.exponential(scale=10,size=10)

array([ 0.41533905,  4.04595912, 29.39721383,  9.61444954,  4.60251087,
        9.46690763,  2.30837494,  1.8040313 ,  4.49130619, 19.90356893])

In [119]:
np.random.uniform(low=10,high=20,size=5)

array([15.09401727, 12.96901516, 19.50251625, 18.1596609 , 13.22973943])

In [120]:
np.random.laplace(loc=0,scale=1,size=5)

array([ 2.88591852,  3.67703767, -0.20172426,  0.37374293, -0.20910949])

# Sampling from some standard distributions

In [121]:
np.random.standard_normal(10)

array([-1.01229175, -0.32385978, -0.18829686, -0.90000857, -0.931002  ,
       -1.22273696, -0.39331085, -0.95758184,  2.05646734, -1.88849238])

In [122]:
np.mean(np.random.standard_exponential(100))

1.0665173576639133

In [123]:
np.random.standard_t(2,10)

array([-1.28463286, -0.6982525 ,  1.37349904,  0.03891925, -0.59407886,
        0.03539451, -3.85049431, -0.48148219,  0.57479552,  3.80819648])

In [124]:
np.random.standard_gamma(2,10)

array([0.50740207, 3.44665378, 1.76684472, 2.16648909, 1.1743428 ,
       0.57397202, 0.69744557, 2.11117868, 2.97103095, 1.74203881])

# Shuffle an array in place

In [261]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [126]:
np.random.shuffle(arr)
print(arr)

[2 1 5 6 7 0 8 3 4 9]


# Generate a permutation of an array

In [127]:
# similar to np.random.shuffle(), but it returns a copy rather than making changes in place
arr = np.array(range(10))
print('A permutation of the array: ', np.random.permutation(arr))
print('The initial array: ', arr)

A permutation of the array:  [6 5 7 4 0 8 3 9 2 1]
The initial array:  [0 1 2 3 4 5 6 7 8 9]


# Math Functions

In [128]:
arr = np.random.randint(1,9,size=(3,3))
arr

array([[4, 5, 6],
       [3, 5, 8],
       [7, 6, 4]])

# element-wise operations

In [129]:
print(arr + 10) # addition, subtraction, multiplication and division
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[14 15 16]
 [13 15 18]
 [17 16 14]]
[[-6 -5 -4]
 [-7 -5 -2]
 [-3 -4 -6]]
[[40 50 60]
 [30 50 80]
 [70 60 40]]
[[0.4 0.5 0.6]
 [0.3 0.5 0.8]
 [0.7 0.6 0.4]]


In [130]:
arr1 = np.array([1,2,3])
arr2=np.array([8,9,10])
arr3=np.add(arr1,arr2)
arr3

array([ 9, 11, 13])

In [131]:
np.subtract(arr1, [8,9,10], out=arr1)
print(arr1)

[-7 -7 -7]


In [132]:
np.multiply([4,5,3], [1,2,3], out=arr1)
print("Multiplication:",arr1)
np.divide([4,6,9],[1,2,3])

Multiplication: [ 4 10  9]


array([4., 3., 3.])

# Element-wise Exponentiation

In [133]:
print(np.exp(arr1))

[   54.59815003 22026.46579481  8103.08392758]


# Element-wise Logorithm

In [134]:
# natural log
print(np.log(arr)) 

[[1.38629436 1.60943791 1.79175947]
 [1.09861229 1.60943791 2.07944154]
 [1.94591015 1.79175947 1.38629436]]


In [135]:
# base 2
print(np.log2(arr)) 

[[2.         2.32192809 2.5849625 ]
 [1.5849625  2.32192809 3.        ]
 [2.80735492 2.5849625  2.        ]]


In [136]:
# base 10
print(np.log10(arr))    

[[0.60205999 0.69897    0.77815125]
 [0.47712125 0.69897    0.90308999]
 [0.84509804 0.77815125 0.60205999]]


# Element-wise square root

In [137]:
print(np.sqrt([1,4,9]))

[1. 2. 3.]


# Element-wise sine and cosine

In [140]:
print(np.sin(arr))

[[-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.14112001 -0.95892427  0.98935825]
 [ 0.6569866  -0.2794155  -0.7568025 ]]


In [139]:
print(np.cos(arr))

[[-0.65364362  0.28366219  0.96017029]
 [-0.9899925   0.28366219 -0.14550003]
 [ 0.75390225  0.96017029 -0.65364362]]


# Sum along a specified axis

In [141]:
# Sum along the row
print(arr)
print(np.sum(arr, axis=0))

[[4 5 6]
 [3 5 8]
 [7 6 4]]
[14 16 18]


In [142]:
# sum along the column
print(np.sum(arr, axis=1))  

[15 16 17]


# Compute the min and max along a specified axis

In [143]:
# calculate min along the row
print(np.min(arr, axis=0))

[3 5 4]


In [144]:
# calculate max along the column
print(np.max(arr, axis=1))  

[6 8 7]


In [145]:
# if axis not specified, calculate the max/min value of all elements
print(np.max(arr))
print(np.min(arr))

8
3


# Indices of the min and max along a specified axis

In [146]:
# along the row
print(arr)
print(np.argmin(arr, axis=0)) # Index of Column Minimum
print(np.argmax(arr, axis=0)) # Index of Row Minimum

[[4 5 6]
 [3 5 8]
 [7 6 4]]
[1 0 2]
[2 2 1]


In [147]:
# along the column
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))

[0 0 2]
[2 2 0]


In [148]:
# if axis not specified, return the index of the flattened array
print(np.argmin(arr))
print(np.argmax(arr))

3
5


# Element-wise min and max of two arrays

In [149]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


# Split fractional and integral parts of a floating-point array

In [150]:
arr1 = np.random.rand(5) * 100
re, intg = np.modf(arr1)
print("Original :", arr1)
print('integral: ', intg)
print('fractional: ', re)

Original : [ 2.75429297  3.19179876 70.1359801  70.75811186 95.99391337]
integral:  [ 2.  3. 70. 70. 95.]
fractional:  [0.75429297 0.19179876 0.1359801  0.75811186 0.99391337]


# Compute the mean

In [151]:
# compute the overall mean
print(np.mean(arr))

5.333333333333333


In [152]:
# compute the mean along the row
print(np.mean(arr, axis=0))  

[4.66666667 5.33333333 6.        ]


In [153]:
# compute the mean along the column
print(np.mean(arr, axis=1)) 

[5.         5.33333333 5.66666667]


# Median

In [154]:
# compute the overall median
print(np.median(arr))

5.0


In [155]:
# compute the median along the row
print(np.median(arr, axis=0)) 

[4. 5. 6.]


In [156]:
# compute the median along the column
print(np.median(arr, axis=1))

[5. 5. 6.]


# Compute the percentile

In [157]:
arr1 = np.random.rand(100)
# print(arr1)
# compute 5, 65, and 95 percentiles of the array
print(np.percentile(arr1, [50, 60, 90]))

[0.48267405 0.63449797 0.94482371]


# Compute the standard deviation & variance

In [158]:
# compute the overall standard deviation
print(np.std(arr))

1.4907119849998598


In [159]:
# compute the standard deviation along the row
print(np.std(arr, axis=0))

[1.69967317 0.47140452 1.63299316]


In [160]:
# compute the standard deviation along the column
print(np.std(arr, axis=1))

[0.81649658 2.05480467 1.24721913]


In [161]:
# compute the overall variance
print(np.var(arr))

2.2222222222222223


In [162]:
# compute the variance along the row
print(np.var(arr, axis=0))

[2.88888889 0.22222222 2.66666667]


In [163]:
# compute the variance along the column
print(np.var(arr, axis=1))

[0.66666667 4.22222222 1.55555556]


# Compute the covariance & correlation

In [164]:
arr = np.random.rand(5,3)
print(arr)

[[0.01501615 0.87914244 0.06393855]
 [0.7333954  0.99461039 0.50118978]
 [0.20933399 0.59464358 0.62414998]
 [0.66807274 0.17261174 0.89871269]
 [0.62099137 0.0435687  0.68404106]]


In [165]:
print(np.cov(arr))

[[ 0.23561084  0.10276685  0.05486604 -0.16812962 -0.16966619]
 [ 0.10276685  0.0609361  -0.0017055  -0.09020848 -0.08024903]
 [ 0.05486604 -0.0017055   0.05356774 -0.01230135 -0.02957241]
 [-0.16812962 -0.09020848 -0.01230135  0.13764983  0.1276133 ]
 [-0.16966619 -0.08024903 -0.02957241  0.1276133   0.12459951]]


In [166]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[ 1.         -0.36847081]
 [-0.36847081  1.        ]]


# Compute cumulative sum & product

In [167]:
# calculate the cumulative sums along the row
print(np.cumsum(arr, axis=0)) 

[[0.01501615 0.87914244 0.06393855]
 [0.74841155 1.87375283 0.56512833]
 [0.95774554 2.46839641 1.18927831]
 [1.62581828 2.64100815 2.087991  ]
 [2.24680964 2.68457685 2.77203207]]


In [168]:
# calculate the cumulative sums along the column
print(np.cumsum(arr, axis=1))    

[[0.01501615 0.89415859 0.95809714]
 [0.7333954  1.72800579 2.22919557]
 [0.20933399 0.80397757 1.42812755]
 [0.66807274 0.84068448 1.73939717]
 [0.62099137 0.66456007 1.34860114]]


In [169]:
# calculate the cumulative product along the row
print(np.cumprod(arr, axis=0)) 

[[0.01501615 0.87914244 0.06393855]
 [0.01101277 0.8744042  0.03204535]
 [0.00230535 0.51995885 0.0200011 ]
 [0.00154014 0.089751   0.01797525]
 [0.00095641 0.00391033 0.01229581]]


In [170]:
# calculate the cumulative product along the column
print(np.cumprod(arr, axis=1))

[[0.01501615 0.01320133 0.00084407]
 [0.7333954  0.72944268 0.36558922]
 [0.20933399 0.12447911 0.07769364]
 [0.66807274 0.1153172  0.10363703]
 [0.62099137 0.02705579 0.01850727]]


# Element-wise comparison

In [171]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [172]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]


# Slicing & Indexing

In [173]:
import numpy as np
arr=np.array(range(1,13)).reshape(3,4)

# Row and Column indices

Select an element by row and column indices


In [174]:
print(arr)
print(arr[1][2])
# or more concisely
print(arr[2,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
11


# Indexing with slicing

In [175]:
print(arr)
print(arr[1:,1:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 6  7  8]
 [10 11 12]]


In [176]:
# ellipsis slicing: auto-complete the dimensions
arr = np.array(range(16)).reshape(2,2,2,2)
# print(arr)
# equivalent to arr[0,:,:,:]
print(arr[0, ...]) 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


# Assign a scalar to a slice by broadcasting

In [177]:
print("Original Array is \n",arr)
arr[1:3,:] = 100    # or simply arr[1:3]
arr[:,8:] = 100
print("Array is \n",arr)

Original Array is 
 [[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
Array is 
 [[[[  0   1]
   [  2   3]]

  [[  4   5]
   [  6   7]]]


 [[[100 100]
   [100 100]]

  [[100 100]
   [100 100]]]]


# Boolean Indexing

In [178]:
arr1 = np.arange(25).reshape((5,5))
print(arr1)
list1=[True,False,True,False,True]
arr1[list1]
list2=np.array(['M','F',"M","M","F"])
print(arr1[list2=="M"])
print(arr1[arr1[:,4]>=10])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [179]:
# negate the condition
print(arr1[~(list2=="M")])
#print(arr1[~bools])   

[[ 5  6  7  8  9]
 [20 21 22 23 24]]


In [180]:
arr2 = np.array([1,2,3,4,5])
# multiple conditions
print(arr1[(arr2>=2) & (arr2<=4)])    

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


# Fancy indexing

In [181]:
arr = np.random.rand(10,5)
arr

array([[0.19608405, 0.02734078, 0.55095328, 0.81331364, 0.85994115],
       [0.10352093, 0.66304279, 0.71007522, 0.29451699, 0.971364  ],
       [0.27868747, 0.06998219, 0.51928036, 0.69431489, 0.24465979],
       [0.3385822 , 0.56362798, 0.88667817, 0.74732591, 0.20959196],
       [0.25177707, 0.52388069, 0.76895869, 0.61876178, 0.50132427],
       [0.59712534, 0.75606003, 0.53707979, 0.89775274, 0.94706749],
       [0.91535451, 0.75451834, 0.246321  , 0.38527145, 0.27999995],
       [0.65766024, 0.32422162, 0.7543916 , 0.11350908, 0.77536476],
       [0.58590197, 0.83538869, 0.43087565, 0.62496445, 0.55441213],
       [0.97567127, 0.75547439, 0.54481325, 0.17403209, 0.90411422]])

In [182]:
# select arr[3,3], arr[1,2], arr[2,1]
print(arr[[3,1,2], [3,2,1]])   

[0.74732591 0.71007522 0.06998219]


In [183]:
# select rows 3,1,2 and columns 6,4,8 
print(arr[[3,1,2]][:, [4,2,3]])    

[[0.20959196 0.88667817 0.74732591]
 [0.971364   0.71007522 0.29451699]
 [0.24465979 0.51928036 0.69431489]]


# Dimension inference

In [184]:
# dimension inference using any negative number (usually -1)
arr = np.array(range(20)).reshape((4,-1))
print(arr)
print(arr.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


# Find elements/indices by conditions

In [185]:
arr = np.arange(16).reshape(4,4)

In [186]:
# find the elements greater than 5 and return a flattened array
print(arr[arr>5])    # or arr[np.where(arr>5)]

[ 6  7  8  9 10 11 12 13 14 15]


In [187]:
# return values based on conditions 
# np.where(condition, true_return, false_return)
print(np.where(arr>5, -1, 10))

[[10 10 10 10]
 [10 10 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [188]:
# find the indices of the elements on conditions
print(np.argwhere(arr>5))

[[1 2]
 [1 3]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [3 0]
 [3 1]
 [3 2]
 [3 3]]


# Sort an Array

In [189]:
arr = np.random.rand(3,3)
arr

array([[0.20583778, 0.65004326, 0.93647185],
       [0.22357963, 0.22592354, 0.85181891],
       [0.82765503, 0.35170335, 0.26509629]])

# Sort an array along a specified axis

In [190]:
# sort along the row and return a copy
print(np.sort(arr, axis=0))  

[[0.20583778 0.22592354 0.26509629]
 [0.22357963 0.35170335 0.85181891]
 [0.82765503 0.65004326 0.93647185]]


In [191]:
# sort along the row in place
arr.sort(axis=0)
print(arr)

[[0.20583778 0.22592354 0.26509629]
 [0.22357963 0.35170335 0.85181891]
 [0.82765503 0.65004326 0.93647185]]


In [192]:
# sort along the column and return a copy
print(np.sort(arr, axis=1))    

[[0.20583778 0.22592354 0.26509629]
 [0.22357963 0.35170335 0.85181891]
 [0.65004326 0.82765503 0.93647185]]


# compute the indices that would sort an array along a specified axis

In [193]:
arr = np.random.rand(5,5)

In [194]:
# along the row
print(np.argsort(arr, axis=0))

[[1 1 4 3 2]
 [0 2 3 2 0]
 [4 4 1 4 3]
 [3 3 2 0 4]
 [2 0 0 1 1]]


In [195]:
# along the column
print(np.argsort(arr, axis=1))

[[0 4 2 3 1]
 [1 0 2 3 4]
 [1 4 3 2 0]
 [3 2 1 4 0]
 [2 0 3 1 4]]


In [196]:
# if axis=None, return the indices of a flattened array
print(np.argsort(arr, axis=None))

[ 6 18  5  0 11 14 13 22 17  7 20 23 21 12 16  4 19 24 15  2 10  3  8  9
  1]


# Manipulate an Array
transpose an array



In [197]:
# the following methods return a copy
arr=np.array(range(15)).reshape(3,5)
print(arr.T)
# or 
print(np.transpose(arr))
# or
print(arr.transpose())

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


# transpose of a high dimensional array with specified order of axes

In [198]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1)

arr1.transpose((1,0,2))
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


# swap axes

In [199]:
arr1 = np.arange(16).reshape((2,2,4))
print(arr1.swapaxes(1,2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


# change the shape of an array

In [200]:
# change the shape of an array and return a copy
arr=np.array(range(12))
print(arr.reshape(2,6))
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [201]:
# change the shape of an array in place
arr.resize((2,6))
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

# flatten an array

In [202]:
x=arr.flatten() # return a copy
x[2]=100
print(x)
print(arr)

[  0   1 100   3   4   5   6   7   8   9  10  11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [203]:
# change any element in the view will change the initial array
y=arr.ravel()   # return a view
y[2]=100
print(y)
print(arr)

[  0   1 100   3   4   5   6   7   8   9  10  11]
[[  0   1 100   3   4   5]
 [  6   7   8   9  10  11]]


# append elements to an array

In [204]:
arr = np.array([1,2,3])
# append a scalar and return a copy
arr1 = np.append(arr, 4)    
print(arr1)

[1 2 3 4]


In [205]:
# append an array and return a copy
arr2 = np.append(arr, [4,5,6])    
print(arr2)

[1 2 3 4 5 6]


In [206]:
L1=[1,2,3]
L2=[4,5,6]
L1.extend(L2)
print(L1)

[1, 2, 3, 4, 5, 6]


# Insert elements into an array

In [214]:
# np.insert(array, position, element)
# insert a scalar at a certain position
print(arr)
arr3 = np.insert(arr, 0, 100)    
print(arr3)

[1 2 3]
[100   1   2   3]


In [215]:
# insert multiple values at a certain position
arr3 = np.insert(arr, 0, [1,2,3])    
print(arr3)

[1 2 3 1 2 3]


# delete elements from an array

In [216]:
# remove the element at position 0
arr4 = np.delete(arr, 0)    
print(arr4)

[2 3]


In [217]:
# remove the element at multiple positions
arr4 = np.delete(arr, [0,2])    
print(arr4)

[2]


# Copy an array

In [218]:
arr = np.array([1,2,3])

In [219]:
# the following methods are all deep copy
arr1 = np.copy(arr)
# or 
arr1 = arr.copy()
# or 
arr1 = np.array(arr, copy=True)
arr1[1]=20
print(arr)

[1 2 3]


# Combine & Split an Array

In [220]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [221]:
# concat along the row
cat = np.concatenate((arr1, arr2), axis=0)        
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [222]:
# concat along the column
cat = np.concatenate((arr1, arr2), axis=1)    
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [223]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [224]:
# stack arrays vertically
cat = np.r_[arr1, arr2]
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [225]:
# stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [226]:
# stack arrays horizontally
cat = np.c_[arr1, arr2]
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


# Split an array

In [227]:
arr = np.random.rand(4,4)

In [228]:
# split the array vertically into n evenly spaced chunks
arr1 = np.vsplit(arr, 2)
print(arr1)

[array([[0.01414381, 0.847647  , 0.92191986, 0.55052969],
       [0.26802112, 0.990239  , 0.38319403, 0.69365539]]), array([[0.68995255, 0.43430906, 0.19915816, 0.96657938],
       [0.06369086, 0.48514939, 0.22073071, 0.29397413]])]


In [229]:
# split the array horizontally into n evenly spaced chunks
arr2 = np.hsplit(arr, 2)
print(arr2)

[array([[0.01414381, 0.847647  ],
       [0.26802112, 0.990239  ],
       [0.68995255, 0.43430906],
       [0.06369086, 0.48514939]]), array([[0.92191986, 0.55052969],
       [0.38319403, 0.69365539],
       [0.19915816, 0.96657938],
       [0.22073071, 0.29397413]])]


# Set Operations
Select the unique elements from an array



In [230]:
arr = np.array([1,1,2,2,3,3,4,5,6])
print(np.unique(arr))

[1 2 3 4 5 6]


In [231]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


# Intersection & union of two arrays

In [232]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [233]:
# intersection
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [234]:
# union
print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


# Compute whether each element of an array is contained in another


In [239]:
print(np.in1d([1,2,3,4,5], [1,2,3]))

[ True  True  True False False]


In [240]:
# preserve the shape of the array in the output, if the array is of higher dimensions
arr1=np.array(range(10)).reshape(2,5)
arr2=np.array(range(6,15))
print(np.isin(arr1, arr2))

[[False False False False False]
 [False  True  True  True  True]]


# Compute the elements in an array that are not in another

In [241]:
print("Array1:\n",arr1.flatten())
print("Array2:\n",arr2)
print(np.setdiff1d(arr1, arr2))

Array1:
 [0 1 2 3 4 5 6 7 8 9]
Array2:
 [ 6  7  8  9 10 11 12 13 14]
[0 1 2 3 4 5]


# Compute the elements in either of two arrays, but not both

In [242]:
print(np.setxor1d(arr1, arr2))

[ 0  1  2  3  4  5 10 11 12 13 14]


# Linear Algebra

In [243]:
arr1 = np.array(range(4)).reshape(2,2)
arr2 = np.array(range(5,9)).reshape(2,2)
print(arr1)
print(arr2)

[[0 1]
 [2 3]]
[[5 6]
 [7 8]]


# Matrix Multiplication

In [244]:
print(arr1.dot(arr2))# or
print(np.dot(arr1, arr2))# or
print(arr1 @ arr2)

[[ 7  8]
 [31 36]]
[[ 7  8]
 [31 36]]
[[ 7  8]
 [31 36]]


# QR Factorization

In [245]:
arr = np.random.rand(2,2)
q, r = np.linalg.qr(arr) # Factor the matrix arr as qr, where q is orthonormal and r is upper-triangular.
print("q:\n",q)
print("r:\n",r)
print("Matrix:\n",arr)
print("qr :\n",q.dot(r))

q:
 [[-0.9949781 -0.1000929]
 [-0.1000929  0.9949781]]
r:
 [[-0.83270911 -0.38507033]
 [ 0.          0.15856248]]
Matrix:
 [[0.82852732 0.36726556]
 [0.08334827 0.19630901]]
qr :
 [[0.82852732 0.36726556]
 [0.08334827 0.19630901]]


# Singular Value Decomposition (SVD)

In [246]:
arr = np.random.rand(2,2)
u, s, v = np.linalg.svd(arr)
print("u\n",u)
print("s\n",s)
print("v\n",v)

u
 [[-0.87978277 -0.47537593]
 [-0.47537593  0.87978277]]
s
 [1.47511773 0.21644214]
v
 [[-0.5995006 -0.8003743]
 [-0.8003743  0.5995006]]


# Eigen values

In [247]:
arr = np.random.randint(0,10,(3,3))
print(np.linalg.eigvals(arr))

[16.88536503 -0.86184557 -3.02351946]


# Eigen value decomposition

In [248]:
arr = np.random.randint(0,10,(3,3))
print("Matrix:\n",arr)
e, v = np.linalg.eig(arr)
print("Eigen Values: ",e)    
print("Eigen Vectors:\n",v)

Matrix:
 [[4 1 3]
 [5 8 4]
 [2 8 9]]
Eigen Values:  [15.57631803+0.j          2.71184098+2.27264675j  2.71184098-2.27264675j]
Eigen Vectors:
 [[ 0.25129996+0.j          0.1653597 +0.53289295j  0.1653597 -0.53289295j]
 [ 0.57637918+0.j          0.44957085-0.31064667j  0.44957085+0.31064667j]
 [ 0.77758303+0.j         -0.62455262+0.j         -0.62455262-0.j        ]]


# Trace & Determinant

In [249]:
# notice this is not a function in linalg!!!
print(np.trace(arr))  

21


In [250]:
print(np.linalg.det(arr))

195.0


# Inverse/psedo-inverse of a matrix

In [251]:
arr=np.random.randint(0,10,(3,3))
print("Matrix:\n",arr)
print("Inverse of a matrix:\n",np.linalg.inv(arr))

Matrix:
 [[3 6 2]
 [9 8 0]
 [5 0 7]]
Inverse of a matrix:
 [[-0.19310345  0.14482759  0.05517241]
 [ 0.21724138 -0.03793103 -0.06206897]
 [ 0.13793103 -0.10344828  0.10344828]]


In [252]:
print("Psudo-inverse of a matrix:\n",np.linalg.pinv(arr))

Psudo-inverse of a matrix:
 [[-0.19310345  0.14482759  0.05517241]
 [ 0.21724138 -0.03793103 -0.06206897]
 [ 0.13793103 -0.10344828  0.10344828]]


# Solve a Linear System

In [253]:
# Solve a linear system in closed form

print("Matrix:\n",arr)
y = [1,2,3]
print(np.linalg.solve(arr, y))

Matrix:
 [[3 6 2]
 [9 8 0]
 [5 0 7]]
[ 0.26206897 -0.04482759  0.24137931]


In [254]:
# Calculate the least-squares solution of a linear system

In [256]:
y = [3,4,5]
solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
print(solution)
print(residuals)
print(rank)
print(singular)

[0.27586207 0.18965517 0.51724138]
[]
3
[14.40230742  7.27397624  2.76817819]


C:\Users\FLUTE\AppData\Local\Temp/ipykernel_12192/1258724668.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  solution, residuals, rank, singular = np.linalg.lstsq(arr, y)
